In [84]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/data analyst /Pertemuan 26/scraped_Petualangan_Jokowi.csv')   # ganti dengan file Anda
print('Dimensi data:', df.shape)
df.head()

Dimensi data: (2162, 4)

,id,teks,tanggal,sumber
0,f135b7dc-8e98-43c5-923d-e1742ff7d8e7,"gimana ya? game nya bagus sih standar tapi,leb...",8/15/2026 6:02,playstore
1,8a11dac5-9c93-48ea-8e3a-c3ff200d8bd2,Bagus sih. Cuman lawannya makin lama makin jag...,2/28/2026 8:54,playstore
2,8672a955-03af-4b0c-bc5c-bb5ba7569083,Gamenya sudah bagus dari segi grafik dan cerit...,7/25/2025 19:39,playstore
3,1c343500-cac6-46d4-b0d1-b1d0aeb6a4a4,untuk game nya sudah bagus ya walaupun level n...,5/26/2026 5:57,playstore
4,3d3c74de-2687-4426-9510-8127546d5d90,"saran gw si, ni game bagus sebenernya, tapi ta...",12/8/2025 10:20,playstore

In [85]:
positif = [
    'bagus', 'mantap', 'puas', 'keren', 'kerennn', 'top', 'oke', 'baik', 'memuaskan',
    'nyaman', 'suka', 'love', 'best', 'hebat', 'terbaik', 'sukses', 'lancar', 'aman',
    'seru', 'kocak', 'lucu', 'menghibur', 'kreatif', 'salut', 'asyik', 'gg', 'gokil',
    'tamat', 'nagih', 'karya anak bangsa', 'bangga'
]

negatif = [
    'buruk', 'jelek', 'kecewa', 'mengecewakan', 'parah', 'kapok', 'sampah', 'norak', 'najis',
    'lambat', 'lama', 'lemot', 'rusak', 'error', 'hilang', 'ilang', 'bug', 'ngebug','susah',
    'ngelag', 'lag', 'kaku', 'delay', 'iklan', 'bosen', 'bosan', 'macet','berat', 'kurang',
    'patah', 'nyangkut','bintang 1', 'bintang satu', 'uninstal', 'hapus', 'copot', 'burik','jmbt'
]

print('Jumlah kata positif (Game):', len(positif))
print('Jumlah kata negatif (Game):', len(negatif))

Jumlah kata positif (Game): 31
Jumlah kata negatif (Game): 38

In [86]:
def auto_label(teks):
    if not isinstance(teks, str):
        return 'netral'
    t = teks.lower()
    skor_pos = sum(1 for k in positif if k in t)
    skor_neg = sum(1 for k in negatif if k in t)

    if skor_pos > skor_neg:
        return 'positif'
    elif skor_neg > skor_pos:
        return 'negatif'
    else:
        return 'netral'

df['sentimen_auto'] = df['teks'].apply(auto_label)
print(df['sentimen_auto'].value_counts())
df.head(10)

sentimen_auto
netral     1085
positif     870
negatif     207
Name: count, dtype: int64

,id,teks,tanggal,sumber,sentimen_auto
0,f135b7dc-8e98-43c5-923d-e1742ff7d8e7,"gimana ya? game nya bagus sih standar tapi,leb...",8/15/2026 6:02,playstore,netral
1,8a11dac5-9c93-48ea-8e3a-c3ff200d8bd2,Bagus sih. Cuman lawannya makin lama makin jag...,2/28/2026 8:54,playstore,negatif
2,8672a955-03af-4b0c-bc5c-bb5ba7569083,Gamenya sudah bagus dari segi grafik dan cerit...,7/25/2025 19:39,playstore,netral
3,1c343500-cac6-46d4-b0d1-b1d0aeb6a4a4,untuk game nya sudah bagus ya walaupun level n...,5/26/2026 5:57,playstore,netral
4,3d3c74de-2687-4426-9510-8127546d5d90,"saran gw si, ni game bagus sebenernya, tapi ta...",12/8/2025 10:20,playstore,positif
5,442c0de6-1208-4a03-8c3e-c96915970338,"Game nya bagus banget, salut ama developer yg ...",7/13/2021 2:32,playstore,positif
6,54781cef-a72e-4420-935e-518ffc1560ff,"Bagus bang game nya dari karakter,stagenya, te...",7/27/2021 10:08,playstore,negatif
7,9fedbb70-ab9c-4cbc-b155-da3281cb49a4,tolong kembalikan beberapa ciri khas dari game...,8/6/2025 11:40,playstore,positif
8,c8f06374-2c0a-4321-b3f4-6fdb22424fc6,"Bug tembus tembok, jalan di jalanan yang ada s...",1/9/2021 21:05,playstore,negatif
9,d34a85fb-8ca3-4b5e-b018-489df83c993e,Game nya sudah bagus cuma ada saran yg ingin s...,5/23/2022 15:40,playstore,negatif

In [94]:
sample = df.head (50).copy()
sample['sentimen_manual'] = ''
sample.to_csv('untuk_koreksi_manual.csv', index=False)

In [96]:
# Setelah dikoreksi di Excel/Sheets, simpan kembali sebagai 'sudah_dikoreksi.csv' lalu muat:
pd.read_csv('/content/sudah_dikoreksi.csv')

,id,teks,tanggal,sumber,sentimen
0,b00fa8a8-7720-4c0e-b4df-3b7eec681e1f,woww keren,8/18/2026 5:50,playstore,positif
1,f135b7dc-8e98-43c5-923d-e1742ff7d8e7,"gimana ya? game nya bagus sih standar tapi,leb...",8/15/2026 6:02,playstore,netral
2,333d8aac-da87-4a71-b7e9-24b20d29b70a,game nya bagus🥰,8/9/2026 9:41,playstore,positif
3,bcb6b1f4-6ccf-4476-b500-3581fe0ed035,kalo ketemu VM jangan di lawan lari aja nanti ...,8/9/2026 8:20,playstore,netral
4,a2fcfa58-2cb4-425d-9dd8-0bfae972da40,mana jokowinya??,8/6/2026 3:11,playstore,netral
5,94326b69-7d41-47be-b9ca-3599d25863f0,masih banyak banget bug nya tpi gameplay nya seru,7/18/2026 1:32,playstore,netral
6,96dd5d05-b7cc-409b-a238-5f3da16bc27f,gacor Jokowi,7/14/2026 0:39,playstore,netral
7,176f53d0-0aeb-490e-a30f-eafd0e90a232,Karena saat saya keluar dari game karakter nya...,7/13/2026 23:13,playstore,negatif
8,611a0533-a400-40ba-9057-07e25dcbe7ff,kurang mas Anies doang,7/9/2026 14:08,playstore,netral
9,f5028554-56cd-465c-86d4-a38562861272,bagus,7/6/2026 8:30,playstore,positif
10,22988db3-b456-4239-87c0-cc1e6843da8b,GG lah intinya ytta aja lah,7/4/2026 6:05,playstore,positif
11,a46a3e1f-d192-46a1-a900-71c0821d3300,game yan bagus tapi gua masuk pah keluar game ...,6/30/2026 9:04,playstore,netral
12,5f641b2b-c71b-439f-b875-f547ab069e21,Owi sangat op dengan combo yang bisa membelah ...,6/30/2026 8:47,playstore,netral
13,9f194346-eeec-420a-9d62-4548ed9c21e0,game nya bagus dan kocak,6/28/2026 6:09,playstore,positif
14,24b7348d-9840-43e5-afaa-1ddb78d77da2,Kok qku gak bisa nonton iklan untuk dapetin ka...,6/23/2026 4:50,playstore,netral
15,db7fad36-eb9f-47db-8030-0e11d01fefbd,game nya seru sekali tapi bagaimana Cara membu...,6/12/2026 10:47,playstore,positif
16,d553a955-1f2d-4d46-b3fd-b48deccf009c,saya sangat menikmati game ini tapi saya kecew...,6/11/2026 2:45,playstore,negatif
17,9a7b95c9-d369-43d3-91c5-145f74881008,saya akan lawan,6/10/2026 9:44,playstore,netral
18,b39aabc9-e3cf-4a99-bc41-0a840b2f223b,saya akan lawan,6/3/2026 15:36,playstore,netral
19,1c343500-cac6-46d4-b0d1-b1d0aeb6a4a4,untuk game nya sudah bagus ya walaupun level n...,5/26/2026 5:57,playstore,netral
20,5d1df129-2f97-4b2b-9040-54026d1bfc78,banyak bug,5/25/2026 7:47,playstore,negatif
21,47ad0c42-7a2e-419c-ac78-dc835d8f1f69,game nya bagus saya suka tidak ada bug dan gam...,5/20/2026 14:02,playstore,positif
22,3ca914b7-22b6-41af-8ec6-e9fe6d6e52ac,game ini tidak bagus karna pemerintah tolol,5/17/2026 2:09,playstore,negatif
23,b378fc35-f539-4752-b5bd-2173873fe7cc,biasa aja,5/15/2026 12:47,playstore,netral
24,8fa13a38-5814-4391-b69e-12fbfe0bc619,saran dong adain karakter gibran,5/13/2026 13:12,playstore,netral
25,4f1defc9-3733-4da1-ab62-08f0872051b0,miripin lgi sm jokowi😹,5/13/2026 0:05,playstore,netral
26,3537ae69-cba3-4302-afa5-cb47b6df5b2c,GILAKK KEREN ABISS🥶,5/12/2026 14:26,playstore,positif
27,755cd1eb-1f6a-4ffa-98f7-f981148b7044,saya akan lawan!!!!,5/7/2026 6:31,playstore,netral
28,5db6c244-1cee-4013-8c11-a9c66b36d3c4,game simpel tapi seruuuu bagettt,5/2/2026 11:45,playstore,positif
29,ac252413-52ac-4ad7-8d93-5afeed08cf5d,gokil nih game bagus cuy cuman saran aja tamba...,5/1/2026 6:28,playstore,positif
30,758ad712-2d77-4acc-81df-cbc177b05c68,cihuyyyy,4/29/2026 16:56,playstore,netral
31,84efcf0f-7e63-49f4-aed1-96b6a0e22107,mantap game nya bagus tapi jelek soal nya kura...,4/27/2026 13:31,playstore,positif
32,da890d2f-ca7f-4cc7-9974-50a9cd2f8200,sangat wowo dan pria solo,4/27/2026 13:24,playstore,netral
33,d3cde8a7-eebe-4c34-a607-aeb5a5f4701a,hidup jokowiiiiiii,4/22/2026 8:31,playstore,netral
34,ac2810ee-625c-4399-b646-b10fa051e4a2,DEY BUSUK GAME NYA KIKIR BUKA KARAKTER AJA NON...,4/18/2026 7:44,playstore,negatif
35,740ef76f-b50c-4185-88ca-3e630e87a945,ssngat seru,4/18/2026 3:01,playstore,positif
36,d98893a8-6f54-43f2-90dc-91c103cc03f0,jokowiooooooy,4/17/2026 6:42,playstore,netral
37,d6fe5b9e-776b-4dc7-bf9a-b32d0e50a683,gamenya kek jmbt engga ada zilong sama Alok😎,4/11/2026 0:15,playstore,negatif
38,63898604-ef41-477c-a94f-eac97061c4ae,nama doang petualangan joko gj🗿,4/10/2026 13:27,playstore,netral
39,8706440e-60d4-46a2-b237-4c259f7f9f2d,seru sih tapi kenapa layar gua kok hitam,4/8/2026 13:39,playstore,positif
40,dd03eede-686e-4753-9f05-5e66204c58ea,mantap banget,4/7/2026 10:04,playstore,positif
41,ed468b8d-b98c-46d2-8bdf-35499394f5ae,ah mungkin perasaan ku saja...,4/7/2026 5:07,playstore,netral
42,82a9a7ed-cbdc-4d52-8e6a-c2ea8a0d48f5,mantap,4/7/2026 3:39,playstore,positif
43,c234d0e0-859a-4a31-994f-883a668020e3,burik,4/4/2026 13:12,playstore,negatif
44,0ef1fde2-b548-455d-99bb-547e3028422d,coba perbaiki gamenya. karna kalo saya sudah d...,4/1/2026 9:30,playstore,negatif
45,8d858917-57f9-4264-b9e2-69ec4fccd23d,untuk developer semoga gak ilang ya bang wkwkwkwk,3/30/2026 9:55,playstore,negatif
46,814effc5-b6ea-4208-857b-9cb8d327b6b4,mohon kepada pembuat Cara dapat skin Prabowo I...,3/29/2026 6:14,playstore,netral
47,99e3f476-285c-479a-bffb-e16a467413e0,game ini bagus karna aku selalu memikirkan sawit,3/27/2026 2:02,playstore,positif
48,da3d68f6-5a6c-4e3a-bb4e-d1aaad55a755,gamenya burik kurang hd bikin sakit mata,3/26/2026 17:20,playstore,negatif
49,400e59ce-afc1-433e-bbf2-68f15a63e25b,Dev nya gabut 🗿,3/24/2026 2:38,playstore,netral

In [126]:
# Menghapus semua kolom yang namanya kembar/duplikat (menyisakan satu saja)
df = df.loc[:, ~df.columns.duplicated()]

# Tampilkan hasilnya untuk memastikan tabel sudah rapi
df.head(50)

,id,teks,tanggal,sumber,sentimen
0,f135b7dc-8e98-43c5-923d-e1742ff7d8e7,"gimana ya? game nya bagus sih standar tapi,leb...",8/15/2026 6:02,playstore,netral
1,8a11dac5-9c93-48ea-8e3a-c3ff200d8bd2,Bagus sih. Cuman lawannya makin lama makin jag...,2/28/2026 8:54,playstore,negatif
2,8672a955-03af-4b0c-bc5c-bb5ba7569083,Gamenya sudah bagus dari segi grafik dan cerit...,7/25/2025 19:39,playstore,netral
3,1c343500-cac6-46d4-b0d1-b1d0aeb6a4a4,untuk game nya sudah bagus ya walaupun level n...,5/26/2026 5:57,playstore,netral
4,3d3c74de-2687-4426-9510-8127546d5d90,"saran gw si, ni game bagus sebenernya, tapi ta...",12/8/2025 10:20,playstore,positif
5,442c0de6-1208-4a03-8c3e-c96915970338,"Game nya bagus banget, salut ama developer yg ...",7/13/2021 2:32,playstore,positif
6,54781cef-a72e-4420-935e-518ffc1560ff,"Bagus bang game nya dari karakter,stagenya, te...",7/27/2021 10:08,playstore,negatif
7,9fedbb70-ab9c-4cbc-b155-da3281cb49a4,tolong kembalikan beberapa ciri khas dari game...,8/6/2025 11:40,playstore,positif
8,c8f06374-2c0a-4321-b3f4-6fdb22424fc6,"Bug tembus tembok, jalan di jalanan yang ada s...",1/9/2021 21:05,playstore,negatif
9,d34a85fb-8ca3-4b5e-b018-489df83c993e,Game nya sudah bagus cuma ada saran yg ingin s...,5/23/2022 15:40,playstore,negatif
10,a72de39d-e5c9-4e7c-b517-5984cac8f0e5,Gamenya bagus.tapi aku kasih saran bang 1.kara...,4/23/2021 4:21,playstore,negatif
11,889077fd-35c3-4daf-b78d-536493d7758e,Benerin tuh analognya biar gak susah gerakinny...,7/27/2020 15:35,playstore,positif
12,2ad8d5d0-32f1-4c75-bff4-2257cae30711,"Mantap banget gamenya, cuma yang kurang masala...",3/23/2022 13:12,playstore,positif
13,93a7f1e2-1ed3-41f5-97a5-c1583d6fbed2,"Gameplay game ny baguss bnget, artikulasi tubu...",7/7/2021 12:15,playstore,negatif
14,583fefba-3618-47f2-bc85-9ed8def48319,Antara saat layar disentuh dan respon karakter...,6/24/2021 14:40,playstore,netral
15,f2778012-c888-4010-a2c3-4a10ee73ee9f,Oke langsung ke intinya: tambahin tombol sprin...,8/30/2021 0:53,playstore,positif
16,28ffb645-9854-47de-8d3b-3623db62a424,"Game buatan indo memang kocak😂,beda dari yang ...",8/7/2021 18:41,playstore,positif
17,c29c2709-470f-4216-864a-f44b472fc43d,"Game ny bagus ,grafik ny lumayan ,cuman yang p...",4/26/2022 8:25,playstore,positif
18,9b82c7a0-2964-4188-a02d-4927879617ae,Game ini sungguh bagus. Tapi masih ada bug yg ...,7/4/2021 12:42,playstore,positif
19,22f5ed00-bc4e-4389-a866-9bcf2e8519b8,"Dari segi grafik ok lah, di map ada sedikit bu...",5/10/2021 12:58,playstore,negatif
20,86572719-3525-4051-9494-d0ba047e9ee9,"Ini game keren banget, cuma gua main nya cupu....",6/19/2021 8:49,playstore,netral
21,29ddfa34-40a8-4613-a3fb-2077af02aa85,Gamenya bagus hanya dibiasakan update sesering...,8/12/2020 16:06,playstore,positif
22,76178084-a0b2-484c-9f7e-1376b4227d80,"Bagus gamenya, tapi terkadang saat di setel ke...",7/26/2021 17:00,playstore,negatif
23,e7674426-0655-4ce0-98b9-a43ab5c59706,"Bagus banget , coba ditambah karakter nya , te...",6/22/2021 8:06,playstore,netral
24,c580f1f1-44ff-4dcc-84fe-dd75d1d02dab,"Game nya bagus, cma ada sedikit saran dari say...",1/30/2021 11:56,playstore,positif
25,9661142a-9037-4cb1-8a75-28d43a7168ae,Bagus sih permainannya tapi ada banyak bug. Se...,8/29/2021 2:00,playstore,positif
26,87b819bc-dab3-48e4-9100-1e48769a36d8,Mantap dah pokoknya. Klo bisa ditambahin karak...,5/25/2021 6:17,playstore,positif
27,90ead338-c3aa-487d-8c47-f2e90a9f8e5f,Game yang bagus untuk grafik game ini sudah ke...,4/22/2022 10:22,playstore,negatif
28,fea77106-54ec-4c9b-b2ca-928362c29ef2,"Game nya seru sumpah , tapi Kok levelnya cuma ...",4/30/2021 15:42,playstore,positif
29,79b0678d-af22-426b-a07b-33601463aa99,Saya memainkan game ini karena terlihat unik d...,6/29/2021 3:27,playstore,positif
30,fc6c0823-4885-4342-94e3-d619f0a7df50,"Grafik nya bagus, gameplay juga gampang, sanga...",9/10/2022 10:11,playstore,positif
31,8200d56e-fe7d-4aef-a6f8-8a832ca9aa40,"LMAO PISAN KANG 🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓, sedikit saran da...",10/3/2022 13:02,playstore,netral
32,ce85fc92-b7c7-43a1-9959-2fe6ec1b153e,Ini review saya setelah bermain sampai level 2...,8/11/2020 14:33,playstore,netral
33,b6a566e1-0c3e-4de5-8ecf-06c9cab16b5e,Gamenya bagus banget ada susah ada gampangnya ...,6/9/2023 8:41,playstore,netral
34,24b7348d-9840-43e5-afaa-1ddb78d77da2,Kok qku gak bisa nonton iklan untuk dapetin ka...,6/23/2026 4:50,playstore,netral
35,a3d6d667-3d69-469e-a4fd-2c941ebe6dcc,Kalau bisa tambahkan fitur pvp dan karakter me...,1/3/2020 13:31,playstore,netral
36,4457adf1-76cf-40de-b01f-ef764b0446ac,"tolong updatean selanjutnya dibenerin bug nya,...",7/21/2025 9:28,playstore,negatif
37,b0235512-7d9d-43bd-b41e-333afc97c0a3,Secara umum gamenya seru tapi ada yang kurang ...,6/7/2020 2:44,playstore,netral
38,02bda590-5452-4af1-b0c4-ceb5d39cf1d4,"Gw udah selesaikan semua level, levelnya kuran...",12/18/2025 5:20,playstore,positif
39,b61f38b9-7df1-4801-ae92-9c9119f8cfb3,Wah wah wah mantap gamenya bagus saya sangat s...,12/29/2020 13:30,playstore,positif
40,c3ff375d-7b88-45f2-bc14-32b613d4fc0a,"Bagus, tapi kalo bisa pas musuhnya kelempar ke...",12/6/2025 17:16,playstore,positif
41,c1688b16-622e-47cc-9edc-cfa27f51b920,Gamer nya seruu sih..cuman nyawanya dikit trus...,6/21/2021 11:21,playstore,positif
42,59880486-1d10-411a-aa3a-4cc9f941aa76,Gamenya bagus grafiknya juga udah bagus tapi t...,12/20/2021 23:12,playstore,positif
43,75a6caae-0931-4378-8198-6e4a696390ee,"Wkkwk bagus gamenya, tambahin skill2 karakter,...",1/18/2020 13:12,playstore,negatif
44,d52617ad-c616-4c44-9303-dfb946a78828,Buset pak prabowo sekali tinju udah kayak aldo...,12/18/2020 9:34,playstore,netral
45,3dbc4000-1f3b-49af-a62f-e48a7f4074a4,"Ini Game Sih Bagus Ya Dri Segi Gameplay, Grafi...",6/21/2021 13:08,playstore,netral
46,4e6485ca-c155-4ac7-a673-2f0123dd23f9,gamenya bagus dan seru banget tapi masih ada b...,9/15/2021 12:01,playstore,positif
47,1f041bd2-bc94-451c-8b48-f08a8de98d06,Gameplay lucu+bagus Tapi butuh banyak perbaika...,1/3/2020 13:57,playstore,positif
48,53b807c3-4c37-47fb-8bde-d170c05af8b8,"Baru main sehari dah tamat dan bosen,ini mah g...",2/9/2022 14:37,playstore,netral
49,606ff423-865c-4857-90c4-e88ede75586f,Gamenya bagus Dan seru tapi saya mohon update ...,6/29/2021 2:19,playstore,positif

In [129]:
# 1. Hasilkan sentimen otomatis DULU untuk seluruh data
df['sentimen'] = df['teks'].apply(auto_label)

In [130]:
# 2. Baca data koreksi Anda (Nama kolomnya ternyata 'sentimen')
sample_koreksi = pd.read_csv('sudah_dikoreksi.csv')

In [131]:
# 3. KUNCI PENTING: Timpa 50 baris pertama di df dengan data koreksi manual
df.loc[:49, 'sentimen'] = sample_koreksi['sentimen'].values

In [135]:
# 4. Cek Distribusi Final (3 Kelas)
print("=== Distribusi Sentimen Final (3 Kelas) ===")
print(df['sentimen'].value_counts())

=== Distribusi Sentimen Final (3 Kelas) ===
sentimen
netral     1094
positif     862
negatif     206
Name: count, dtype: int64